INSERT INTO wits.witsEvents (id, title, eventType, summary, eventDate, eventTime, eventLocation, eventLink, author, imageExtension)
VALUES (1, "Resume Revamp", "Recruiting Series", "Join a panel of recruiters from tech companies including Facebook, Google, Twitter and more for tips on recruiting.", "2020-09-02", "17:00:00", "Online", "https://fb.me/e/4sNcXLT6U", "WITS", "recruiting-3.png"),
(2, "Design Technical Interview Prep", "Recruiting Series", "This workshop will be spent learning about design processes, UX/UI, usability testing etc.", "2020-09-23", "17:00:00", "Online", "https://fb.me/e/1xeooznAV", "WITS", "recruiting-1.png"),
(3, "SWE Technical Interview Prep", "Recruiting Series", "Learning about the most common types of coding questions asked during SWE interviews.", "2020-09-24", "17:00:00", "Online", "https://fb.me/e/1DAZrB1N8", "WITS", "recruiting-2.png"),
(4, "PM Technical Interview Prep", "Recruiting Series", "This workshop will be spent learning about Product Sense and Analytical questions.", "2020-09-25", "17:00:00", "Online", "https://fb.me/e/d6qhzEznI", "WITS", "recruiting-4.png"),
(5, "Tech Startups", "Recruiting Series", "Join a panel & network with employees from Asana, Hedera, Figma, Gem, Coursera and Drop.", "2020-10-08", "17:00:00", "Online", "https://fb.me/e/3c4olIGr6", "WITS", "recruiting-5.png"),
(6, "GitHub Overview", "Cookies & Code", "Join a panel & network with employees from Asana, Hedera, Figma, Gem, Coursera and Drop.", "2020-10-08", "17:00:00", "Online", "https://westernuniversity.zoom.us/meeting/register/tJYsf-GhpjIuH9NiSRT0OcI1aIxUXzMywZWR", "WITS", "cookies-code-1.png"),
(7, "Tea & Type: Let's Talk Diversity & Inclusion in Tech", "Cookies & Code", "Grab a warm cup of tea and join a moderated discussion on diversity in tech!", "2020-11-12", "17:00:00", "Online", "https://westernuniversity.zoom.us/meeting/register/tJMoc-GtqzIrEtNGtQuWx2rxRDQdkLh8ZGp8", "WITS", "coming-soon-gray.png"),
(8, "Cookies & Code", "Cookies & Code", "Come join this months casual work night!", "2020-12-07", "17:00:00", "Online", "https://www.facebook.com/wits.uwo", "WITS", "coming-soon-gray.png"),
(9, "Intro to Python", "Workshops", "Come learn the fundamentals of Python and build your first program!", "2020-10-15", "17:00:00", "Online", "https://westernuniversity.zoom.us/meeting/register/tJwsdeyspjIqE9CCVP9f6IjSbHRUOLaHls44", "WITS", "python.png"),
(10, "Intro to UX/UI", "Workshops", "This workshop will be spent learning about design processes, UX/UI, usability testing etc.", "2020-10-29", "17:00:00", "Online", "https://westernuniversity.zoom.us/meeting/register/tJUud-ugpzIrH9K2g5u-F-xW6veOYJj7mAX3", "WITS", "coming-soon-gray.png"),
(11, "Intro to Blockchain with Hedera", "Workshops", "Join a Software Developer from Hedera Hashgraph and discover blockchain tech!", "2020-11-16", "17:00:00", "Online", "https://westernuniversity.zoom.us/meeting/register/tJwvduGspzwiE91y4oxGKom_bafF1sXt_U71", "WITS", "coming-soon-gray.png"),
(12, "Intro to Web Development", "Workshops", "Come out and learn to build your very own website!", "2020-12-07", "17:00:00", "Online", "https://www.facebook.com/wits.uwo", "WITS", "coming-soon-gray.png");

INSERT INTO wits.witsMembers (id, person, title, summary, url, author, imageExtension)
VALUES (1, "Leslie Wu", "Co-President of WITS", "", "https://www.linkedin.com/in/wu-leslie/", "WITS", "leslie.png"),
(2, "Meghan Lo", "Co-President of WITS", "", "http://meghan-lo.com", "WITS", "meghan.png"),
(3, "Elaine Liu", "Chair of SheHacks", "", "http://elaineliu.tech", "WITS", "elaine.png"),
(4, "Jessie Wu", "VP of Operations", "", "https://www.linkedin.com/in/jessie-wu-612ba5169/", "WITS", "jessie.png"),
(5, "Vivian Sun", "Director of SheHacks Design", "", "https://www.linkedin.com/in/vvsn/", "WITS", "vivians.jpg"),
(6, "Connie Yao", "Director of SheHacks", "", "https://www.linkedin.com/in/connieyao00/", "WITS", "conniey.png"),
(7, "Shirley Wang", "Director of SheHacks", "", "https://www.linkedin.com/in/shirley-wang-3b8b5a17a/", "WITS", "shirleywang.png"),
(8, "Sharon Peng", "Director of SheHacks", "", "https://www.linkedin.com/in/pengsharon/", "WITS", "sharon.jpeg"),
(9, "Kisharne Vasikaran", "VP of Events & Educationals", "", "https://www.linkedin.com/in/kisharne-v-53344414b", "WITS", "kisharne.png"),
(10, "Tara Rafi", "VP of Events & Educationals", "", "https://www.linkedin.com/in/tara-rafi/", "WITS", "tara.png"),
(11, "Zoey Zheng", "E&E Director", "", "https://www.linkedin.com/in/zoey-zheng-b31b1718a/", "WITS", "zoey.png"),
(12, "Tala Buwadi", "E&E Director", "", "https://www.linkedin.com/in/tbuwadi/", "WITS", "tala.png"),
(13, "Vivian Xia", "E&E Director", "", "https://www.linkedin.com/in/vivian-xia/", "WITS", "vivianx.png"),
(14, "Selina Yang", "VP of Mentorship & Projects", "", "https://www.linkedin.com/in/selina-ruiqi-yang1999/", "WITS", "selina.jpg"),
(15, "Sammi Yeung", "VP of Mentorship & Projects", "", "https://www.linkedin.com/in/sammiyeung/", "WITS", "sammi.jpg"),
(16, "Celina Shen", "M&P Director", "", "https://www.linkedin.com/in/celina-shen-882562138/", "WITS", "celina.jpeg"),
(17, "Vanessa Lam", "M&P Director", "", "https://www.linkedin.com/in/vanessa-lam-8388341b8/", "WITS", "vanessa.png"),
(18, "Devanshi Shah", "M&P Director", "", "https://www.linkedin.com/in/devanshi-shah-013a5919b/", "WITS", "devanshi.png"),
(19, "Anna Ma", "M&P Director", "", "https://www.linkedin.com/in/anna-ma-6b5835197/", "WITS", "anna.png"),
(20, "Estelle Chung", "VP of Design", "", "https://estellechung.com/design.html", "WITS", "estelle.png"),
(21, "Shirley Wu", "Director of Design", "", "https://www.shirleywu.work/", "WITS", "shirley.png"),
(22, "Jessica Le", "Director of Design", "", "https://www.linkedin.com/in/jessicajxle/", "WITS", "jessica.jpg"),
(23, "Abby Lui", "Director of Design", "", "https://www.linkedin.com/in/abby-lui-70383a1a6/", "WITS", "abby2.jpg"),
(24, "Jenny Cai", "Director of Design", "", "https://www.linkedin.com/in/jenny-cai-3337b8162/", "WITS", "jenny.jpg"),
(25, "Alice Wang", "VP of Development", "", "https://www.linkedin.com/in/alicewang222", "WITS", "alice.png"),
(26, "Janki Chaudhari", "Director of Development", "", "https://www.linkedin.com/in/jankichaudhari/", "WITS", "jankiwits.jpeg"),
(27, "Linda Jiang", "Director of Development", "", "https://www.linkedin.com/in/yu-jie-linda-jiang/", "WITS", "linda.png"),
(28, "Bridget Hart", "Director of Development", "", "https://www.linkedin.com/in/bhart4/", "WITS", "bridget.jpeg"),
(29, "Alex Radova", "VP of Sponsorship", "", "https://www.linkedin.com/in/alexandraradova", "WITS", "alex.png"),
(30, "Judith Chen", "VP of Sponsorship", "", "https://www.linkedin.com/in/judithchen/", "WITS", "judith.png"),
(31, "Amaal Shaikh", "Director of Sponsorship", "", "https://www.linkedin.com/in/amaal-shaikh-b2b1621a5/", "WITS", "amaal.png"),
(32, "Connie Chen", "Director of Sponsorship", "", "https://www.linkedin.com/in/conniechen827/", "WITS", "connie.png"),
(33, "Jinha Kim", "Director of Sponsorship", "", "https://www.linkedin.com/in/jinhakim1999/", "WITS", "jin.jpg"),
(34, "Bonnie Lu", "Director of Sponsorship", "", "https://www.linkedin.com/in/bonnie-lu/", "WITS", "bonnie.jpg"),
(35, "Tito Adebajo", "VP of Finance", "", "https://www.linkedin.com/in/titomi-adebajo/", "WITS", "tito.png"),
(36, "Carrie Lu", "Director of Finance", "", "https://www.linkedin.com/in/carrie-lu-153840175/", "WITS", "carrie.jpg"),
(37, "Kimberley Lu", "VP of Marketing", "", "https://kimlu.myportfolio.com/", "WITS", "kim.png"),
(38, "Samantha McDougall", "Director of Marketing", "", "https://www.linkedin.com/in/samanthamcdougall", "WITS", "sam.png"),
(39, "Jun Huang", "Director of Marketing", "", "https://www.linkedin.com/in/junhuangg/", "WITS", "jun.jpg"),
(40, "Janice Xu", "Director of Marketing", "", "https://www.linkedin.com/in/janicexu16/", "WITS", "janice.jpg"),
(41, "Shareen Siddiqui", "Content Director", "", "https://www.linkedin.com/in/shareen-siddiqui-388a101b5/", "WITS", "shareen.png"),
(42, "Grace Tse", "Content Director", "", "https://www.linkedin.com/in/grace-tse/", "WITS", "grace.jpg");

INSERT INTO wits.blogs (id, title, summary, hyperlink, author, imageExtension)
VALUES (1, "The Ultimate Survival Guide to Social Distancing", "", "https://medium.com/@wits.uwo/the-ultimate-survival-guide-to-social-distancing-e80419fd0329", "WITS", "social.png"),
(2, "Insurance tech: How Telematics and Fitness Devices Are Changing The Industry", "", "https://medium.com/@wits.uwo/insurance-tech-how-telematics-and-fitness-devices-are-changing-the-industry-9a670caa7987", "WITS", "insurance.png"),
(3, "Google’s VP of UX: Designing your own Future", "", "https://medium.com/@wits.uwo/googles-vp-of-ux-designing-your-own-future-3b5271e84b06", "WITS", "googleux.png");

INSERT INTO wits.partners (id, person, company, title, summary, url, author, imageExtension)
VALUES (1, "Erin Chapple", "Microsoft", "Corporate VP, Azure Compute", "", "https://www.linkedin.com/in/erinmchapple/", "WITS", "erin.png"),
(2, "Glaze Martillano", "Facebook", "Talent Acquisition", "", "https://www.linkedin.com/in/glazemartillano/", "WITS", "glaze.png"),
(3, "Melissa Sariffodeen", "Canada Learning Code", "Co-Founder & CEO", "", "https://www.linkedin.com/in/melissasariffodeen/", "WITS", "melissa.png"),
(4, "Stephanie Nyugen", "Coinsquare", "Director of Design", "", "https://www.linkedin.com/in/stephthi/", "WITS", "stephanie.png"),
(5, "Lily Tse", "Think Dirty", "Founder & CEO", "", "https://www.linkedin.com/in/lilytse/", "WITS", "lily.png");

INSERT INTO wits.companies (id, name, url, imageExtension) 
VALUES (1, "Twitter", "https://www.twitter.com", "twitterlogo.png"),
(2, "Facebook", "https://www.facebook.com", "fblogo.png"),
(3, "TD", "https://www.td.com", "tdlogo.png"),
(4, "Microsoft", "https://www.microsoft.com", "microsoftlogo.png"),
(5, "Google", "https://www.google.com", "googlelogo.png"),
(6, "Konrad", "https://www.konrad.com", "konradlogo.png"),
(7, "CPP Investments", "https://www.cppinvestments.com", "cpplogo.png"),
(8, "IBM", "https://www.ibm.com", "ibmlogo.png"),
(9, "Clearbanc", "https://www.clearbanc.com", "cblogo.png"),
(10, "Ubisoft", "https://www.ubisoft.com", "ubisoftlogo.png"),
(11, "Lending Loop", "https://www.lendingloop.ca", "lllogo.png"),
(12, "Scotiabank", "https://www.scotiabank.com", "sblogo.png");
